window.nocturnalBirdsData = [
    {
        id: 1,
        name: "Филин",
        scientific: "Bubo bubo",
        family: "Strigidae",
        activity: "nocturnal",
        image: "images/bubo_bobo.jpg",
        description: "Крупнейшая сова Европы, ведущая ночной образ жизни. Охотится на различных позвоночных.",
        size: "60–75 см",
        wingspan: "150–180 см",
        weight: "1.5–4 кг",
        diet: ["грызуны", "мелкие птицы", "лягушки", "насекомые"],
        habitat: "лесные массивы, скалистые местности",
        rarity: "common",
        sound: "sounds/bubo_bobo.mp3"
    },
    {
        id: 2,
        name: "Белая сова",
        scientific: "Nyctea scandiaca",
        family: "Strigidae",
        activity: "nocturnal",
        image: "images/nyctea_scandiaca.jpg",
        description: "Самая крупная белая сова, приспособленная к суровым условиям Арктики.",
        size: "52–69 см",
        wingspan: "130–160 см",
        weight: "1.5–3 кг",
        diet: ["лемминги", "полёвки", "белые куропатки"],
        habitat: "арктическая зона, тундра",
        rarity: "uncommon",
        sound: "sounds/nyctea_scandiaca.mp3"
    },
    {
        id: 3,
        name: "Болотная сова",
        scientific: "Asio flammeus",
        family: "Strigidae",
        activity: "crepuscular/nocturnal",
        image: "images/asio_flammeus.jpg",
        description: "Средних размеров сова, предпочитающая открытую местность и болота.",
        size: "34–43 см",
        wingspan: "85–105 см",
        weight: "200–500 г",
        diet: ["мыши", "кроты", "насекомые"],
        habitat: "болотные угодья, луга, поля",
        rarity: "common",
        sound: "sounds/asio_flammeus.mp3"
    },
    {
        id: 4,
        name: "Ушастая сова",
        scientific: "Asio otus",
        family: "Strigidae",
        activity: "nocturnal",
        image: "images/asio_otus.jpg",
        description: "Средняя сова с характерными ушными пучками перьев.",
        size: "31–38 см",
        wingspan: "80–100 см",
        weight: "160–400 г",
        diet: ["грызуны", "насекомые", "мелкие птицы"],
        habitat: "разреженные леса, парки, сады",
        rarity: "common",
        sound: "sounds/asio_otus.mp3"
    },
    {
        id: 5,
        name: "Мохноногий сыч",
        scientific: "Aegolius funereus",
        family: "Strigidae",
        activity: "nocturnal",
        image: "images/aegolius_funereus.jpg",
        description: "Небольшая сова с пушистыми ногами, живущая в лесах.",
        size: "20–25 см",
        wingspan: "50–60 см",
        weight: "80–180 г",
        diet: ["мышевидные грызуны", "насекомые"],
        habitat: "темные хвойные леса",
        rarity: "common",
        sound: "sounds/aegolius_funereus.mp3"
    },
    {
        id: 6,
        name: "Бородатая неясыть",
        scientific: "Strix nebulosa",
        family: "Strigidae",
        activity: "nocturnal",
        image: "images/strix_nebulosa.jpg",
        description: "Одна из крупнейших европейских сов, отличается большими размерами и бледным оперением.",
        size: "55–65 см",
        wingspan: "120–140 см",
        weight: "600–1900 г",
        diet: ["грызуны", "мелкие птицы", "ящерицы"],
        habitat: "тайга, смешанные леса",
        rarity: "rare",
        sound: "sounds/strix_nebulosa.mp3"
    },
    {
        id: 7,
        name: "Серая неясыть",
        scientific: "Strix aluco",
        family: "Strigidae",
        activity: "nocturnal",
        image: "images/strix_aluco.jpg",
        description: "Широко распространённая средняя сова с серым оперением.",
        size: "38–48 см",
        wingspan: "85–100 см",
        weight: "300–800 г",
        diet: ["грызуны", "насекомые", "маленькие птицы"],
        habitat: "широколиственные и смешанные леса",
        rarity: "common",
        sound: "sounds/strix_aluco.mp3"
    },
    {
        id: 8,
        name: "Длиннохвостая неясыть",
        scientific: "Strix uralensis",
        family: "Strigidae",
        activity: "nocturnal",
        image: "images/strix_uralensis.jpg",
        description: "Современница тайги, обладающая длинным хвостом и крупными глазами.",
        size: "50–60 см",
        wingspan: "100–120 см",
        weight: "400–800 г",
        diet: ["грызуны", "мелкие птицы", "насекомые"],
        habitat: "тайга, хвойные леса",
        rarity: "common",
        sound: "sounds/strix_uralensis.mp3"
    },
    {
        id: 9,
        name: "Ястребиная сова",
        scientific: "Surnia ulula",
        family: "Strigidae",
        activity: "twilight",
        image: "images/surnia_ulula.jpg",
        description: "Своеобразная сова, внешне похожа на ястреба, живёт в северных лесах.",
        size: "36–41 см",
        wingspan: "65–80 см",
        weight: "250–350 г",
        diet: ["грызуны", "мелкие птицы"],
        habitat: "северные таёжные леса",
        rarity: "common",
        sound: "sounds/surnia_ulula.mp3"
    },
    {
        id: 10,
        name: "Сплюшка",
        scientific: "Otus scops",
        family: "Strigidae",
        activity: "nocturnal",
        image: "images/otus_scops.jpg",
        description: "Мелкая сова с круглыми белыми пятнами на голове, известная своим криком 'сплю' ",
        size: "18–20 см",
        wingspan: "45–55 см",
        weight: "50–100 г",
        diet: ["насекомые", "мелкие беспозвоночные"],
        habitat: "садово-парковые ландшафты, редкие леса",
        rarity: "common",
        sound: "sounds/otus_scops.mp3"
    },
    {
        id: 11,
        name: "Рыбный филин",
        scientific: "Ketupa blakistoni",
        family: "Strigidae",
        activity: "nocturnal",
        image: "images/ketupa_blakistoni.jpg",
        description: "Самый большой рыбоядный филин в мире, эндемик Дальнего Востока России.",
        size: "60–75 см",
        wingspan: "180–200 см",
        weight: "2–4 кг",
        diet: ["рыба", "водяные крысы", "птенцы водоплавающих птиц"],
        habitat: "речные долины Приморского края",
        rarity: "very rare",
        sound: "sounds/ketupa_blakistoni.mp3"
    },
    {
        id: 12,
        name: "Сыч-воробей",
        scientific: "Glaucidium passerinum",
        family: "Strigidae",
        activity: "nocturnal",
        image: "images/glaucidium_passerinum.jpg",
        description: "Миниатюрная сова размером чуть больше воробья, живет в глухих лесных уголках.",
        size: "15–17 см",
        wingspan: "35–40 см",
        weight: "30–70 г",
        diet: ["насекомые", "мелкие мыши", "рептилии"],
        habitat: "густые леса средней полосы России",
        rarity: "common",
        sound: "sounds/glaucidium_passerinum.mp3"
    },
    {
        id: 13,
        name: "Мышелов",
        scientific: "Athene noctua",
        family: "Strigidae",
        activity: "nocturnal",
        image: "images/athene_noctua.jpg",
        description: "Невысокая сова, известный уничтожитель мышей и мелких вредителей.",
        size: "21–28 см",
        wingspan: "55–65 см",
        weight: "100–250 г",
        diet: ["грызуны", "насекомые", "земноводные"],
        habitat: "открытые пространства, парковые зоны",
        rarity: "common",
        sound: "sounds/athene_noctua.mp3"
    },
    {
        id: 14,
        name: "Иглоногая сова",
        scientific: "Ninox japonica",
        family: "Strigidae",
        activity: "nocturnal",
        image: "images/ninox_japonica.jpg",
        description: "Редко встречающаяся в России, прилетает с юга Японии и Китая.",
        size: "28–33 см",
        wingspan: "60–70 см",
        weight: "200–300 г",
        diet: ["насекомые", "мелкие птицы", "мелкие животные"],
        habitat: "тайга, хвойно-широколиственные леса",
        rarity: "rare",
        sound: "sounds/ninox_japonica.mp3"
    },
       {
        id: 15,
        name: "Обыкновенная сипуха",
        scientific: "Tyto alba",
        family: "Tytonidae",
        activity: "nocturnal",
        image: "images/tyto_alba.jpg",
        description: "Единственная представительница семейства Tytonidae в России, легко узнаётся по сердцевидной форме лица.",
        size: "33–39 см",
        wingspan: "85–95 см",
        weight: "250–500 г",
        diet: ["грызуны", "мелкие птицы", "насекомые"],
        habitat: "заброшенные здания, пещеры, пустующие строения",
        rarity: "rare",
        sound: "sounds/tyto_alba.mp3"
    }
];
